services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stellargather_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ag

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - ag

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - ag

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD: password  
      ME_CONFIG_MONGODB_SERVER_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password

    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - ag

  sqlapi:
    build:
      context: ./sql_api
      dockerfile: Dockerfile
    container_name: stellar_gather_sql_api
    ports:
      - "8010:8010"
    environment:
      - DB_HOST=mysql
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=stellargather_db
    depends_on:
      - mysql
    networks:
      - ag

  nosqlapi:
    build:
      context: ./nosql_api
      dockerfile: Dockerfile
    container_name: stellar_gather_nosql_api
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    ports:
      - "8012:8012"
    depends_on:
      - mongodb
    networks:
      - ag
  
  apache:
    image: httpd:latest
    container_name: apache-server
    ports:
      - "8013:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs/
    networks:
      - ag

volumes:
  mysql_data:
  mongo_data:

networks:
  ag:
    external: True
